//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivacyPolicyGeneratorFrontend.WebApp.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_am {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_am() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrivacyPolicyGeneratorFrontend.WebApp.Shared.Resources.Resource.am", typeof(Resource_am).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ስለ እኛ.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ጨምር.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አድራሻ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አደይ.
        /// </summary>
        public static string Adey {
            get {
                return ResourceManager.GetString("Adey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አደይ-ጀነረተር.
        /// </summary>
        public static string Adey_Generator {
            get {
                return ResourceManager.GetString("Adey-Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ማስታወቂያዎችን ለማሳየት.
        /// </summary>
        public static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ዕድሜ.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ሁሉም መብት በ በህግ የተጠበቀ ነው.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ተመለስ እና መልስህን ቀይር.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አጥፋ.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ከተጠቃሚው ጋር ለመገናኘት.
        /// </summary>
        public static string Communicate {
            get {
                return ResourceManager.GetString("Communicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ድርጅት ተወካይ.
        /// </summary>
        public static string CompanyRepresenter {
            get {
                return ResourceManager.GetString("CompanyRepresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to መገናኛ.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የቅጂ መብት.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ፒዲኤፍ አውርድ.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ኢሜይል.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ጾታ.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አመንጭ.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድርጅት መረጃ አመንጭ.
        /// </summary>
        public static string GenerateI {
            get {
                return ResourceManager.GetString("GenerateI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የግላዊነት መመሪያ አመንጭ.
        /// </summary>
        public static string GeneratePP {
            get {
                return ResourceManager.GetString("GeneratePP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ደንብ እና ግዴታ አመንጭ.
        /// </summary>
        public static string GenerateTC {
            get {
                return ResourceManager.GetString("GenerateTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በማመንጨት ላይ....
        /// </summary>
        public static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ጀነረተር.
        /// </summary>
        public static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የግላዊነት መመሪያ, የድርጅት መረጃዎን, እንድሁም ደንብ እና ግዴታዎን አብረውን ይስሩ.
        /// </summary>
        public static string Header1 {
            get {
                return ResourceManager.GetString("Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ለድር ጣቢያዎ እና መተግበሪያዎችዎ የግላዊነት መመሪያ ፣የድርጅት መረጃዎን, እንድሁም ደንብ እና ግዴታዎን, መስራት ለኛ በመተው ግዜዎትንና ጭንቀቶትን ይቀንሱ።ጥቂት ጥያቄዎችን ብቻ በመመለስ ሁሉም የሚጠናቀቅበትን መድረክ አቅርበንልዎታል።.
        /// </summary>
        public static string Header2 {
            get {
                return ResourceManager.GetString("Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to መነሻ ገጽ.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to መነሻ ገጽ.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ቀላል እና ፈጣን ክፍያ በቴሌቢር .
        /// </summary>
        public static string HPTB1 {
            get {
                return ResourceManager.GetString("HPTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የመስመር ላይ ክፍያ ከቴሌቢር ጋር ተቀናጅቷል። ለጥያቄዎች መልስ ከጨረሱ በኋላ ቴሌቢርን በመጠቀም በመስመር ላይ እንዲከፍሉ ይጠየቃሉ። ያለክፍያ ማረጋገጫ የመነጩ ሰነዶችን ማውረድ ወይም መቅዳት እና መለጠፍ አይችሉም።.
        /// </summary>
        public static string HPTB2 {
            get {
                return ResourceManager.GetString("HPTB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300 ኢ.ቢ. / ሰነድ.
        /// </summary>
        public static string HPTB3 {
            get {
                return ResourceManager.GetString("HPTB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በሁለት ቋንቋዎች (በእንግሊዘኛ እና በአማርኛ) የድርጅት መረጃን መፍጠር ይችላሉ። ቅጹን ከመሙላትዎ በፊት የሚፈልጉትን ቋንቋ ይምረጡ። እንዲሁም እባክዎ መልሶችዎ በመረጡት ቋንቋ መሆናቸውን ያረጋግጡ። ተፈላጊ መስኮች.
        /// </summary>
        public static string I_H1 {
            get {
                return ResourceManager.GetString("I-H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የሚከተሉት ጥያቄዎች ትክክለኛ የድርጅት መረጃን ለመፍጠር ይረዱናል። እባክዎን በጣም በጥንቃቄ ይመልሱዋቸው።.
        /// </summary>
        public static string I_H2 {
            get {
                return ResourceManager.GetString("I-H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድርጅት መረጃ ምንድን ነው እና ለምን ያስፈልገናል?.
        /// </summary>
        public static string IH1 {
            get {
                return ResourceManager.GetString("IH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድርጅት መረጃ በመሠረቱ የባለቤትነት እና የደራሲነት መግለጫ ነው። የተጠቃሚ ውሂብን ለመጠበቅ፣የድር ጣቢያ ባለቤቶች እራሳቸውን እንዲለዩ በማድረግ ህገወጥ ይዘትን እና አላስፈላጊ መልዕክትን ለመዋጋት እና በውጤቱም በመድረክ ላይ ላለው ይዘት ሀላፊነት እንዲወስዱ ለማድረግ ነው የተዘጋጀው።.
        /// </summary>
        public static string IH2 {
            get {
                return ResourceManager.GetString("IH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድርጅት መረጃ.
        /// </summary>
        public static string Imprint {
            get {
                return ResourceManager.GetString("Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አገልግሎቱን ለማሻሻል እና ለማዳበር.
        /// </summary>
        public static string Improve {
            get {
                return ResourceManager.GetString("Improve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድርጅት ስም.
        /// </summary>
        public static string IQ1 {
            get {
                return ResourceManager.GetString("IQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድርጅቱ ዓይነት.
        /// </summary>
        public static string IQ2 {
            get {
                return ResourceManager.GetString("IQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድርጅት አድራሻ.
        /// </summary>
        public static string IQ3 {
            get {
                return ResourceManager.GetString("IQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ተጨማሪ አድራሻ.
        /// </summary>
        public static string IQ4 {
            get {
                return ResourceManager.GetString("IQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የንግድ ምዝገባ ቁጥር.
        /// </summary>
        public static string IQ5 {
            get {
                return ResourceManager.GetString("IQ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የተጨማሪ እሴት ታክስ ቁጥር.
        /// </summary>
        public static string IQ6 {
            get {
                return ResourceManager.GetString("IQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የግብር ከፋይ መለያ ቁጥ.
        /// </summary>
        public static string IQ7 {
            get {
                return ResourceManager.GetString("IQ7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ኩባንያውን የሚወክለው ማን ነው?.
        /// </summary>
        public static string IQ8 {
            get {
                return ResourceManager.GetString("IQ8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የእርስዎ ድህረገፅ ሌላ የድህረገፅ አገናኞችን ያቀርባል?.
        /// </summary>
        public static string IQ9 {
            get {
                return ResourceManager.GetString("IQ9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በዳሰሳ አሞሌው ላይ &quot;አመንጭ&quot; የሚለውን ይጫኑ.
        /// </summary>
        public static string IStep1 {
            get {
                return ResourceManager.GetString("IStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በሞሌው ውስጥ &quot; የድርጅት መረጃ’’ይምረጡ ወይም ከታች ያለውን አዝራር ይጫኑ.
        /// </summary>
        public static string IStep2 {
            get {
                return ResourceManager.GetString("IStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ቅጾቹን በትክክል ይሙሉ እና ፣.
        /// </summary>
        public static string Istep3 {
            get {
                return ResourceManager.GetString("Istep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በመጨረሻም አመንጭ የሚለውን ይጫኑ.
        /// </summary>
        public static string Istep4 {
            get {
                return ResourceManager.GetString("Istep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ቋንቋ.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ይዘርዝሩ.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አካባቢ.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ስም.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አይ.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ቢሮ.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ቦሌ ክፍለ ከተማ ወረዳ 12.
        /// </summary>
        public static string Office1 {
            get {
                return ResourceManager.GetString("Office1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የቤት ቁጥር: አዲስ.
        /// </summary>
        public static string Office2 {
            get {
                return ResourceManager.GetString("Office2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አዲስ አበባ፣ ኢትዮጵያ.
        /// </summary>
        public static string Office3 {
            get {
                return ResourceManager.GetString("Office3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በ(,) ነጥለው የሚሰበስቡትን ሌላ ውሂብ ይዘርዝሩ.
        /// </summary>
        public static string OtherDatas {
            get {
                return ResourceManager.GetString("OtherDatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በ(,) ነጥለው ሌሎች ዓላማዎችን ይዘርዝሩ.
        /// </summary>
        public static string OtherPusposes {
            get {
                return ResourceManager.GetString("OtherPusposes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ሌሎች.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የግላዊነት ፖሊሲን በሁለት ቋንቋዎች (እንግሊዝኛ እና አማርኛ) መፍጠር ይችላሉ። ቅጹን ከመሙላትዎ በፊት እባክዎ የመረጡትን ቋንቋ ይምረጡ። እንዲሁም፣ እባክዎ መልሶችዎ በመረጡት ቋንቋ መሆናቸውን ያረጋግጡ። የሚያስፈልጉ መስኮች.
        /// </summary>
        public static string P_PH1 {
            get {
                return ResourceManager.GetString("P-PH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የሚከተሉት ጥያቄዎች ትክክለኛ የግላዊነት ፖሊሲ ለመፍጠር ይረዱናል። እባክዎን በጣም በጥንቃቄ ይመልሱዋቸው።.
        /// </summary>
        public static string P_PH2 {
            get {
                return ResourceManager.GetString("P-PH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ቅጾቹን መሙላት ሲጨርሱ ይህ አዝራር ንቁ ይሆናል። እባኮን ቋንቋ መምረጡን ያረጋግጡ እና ሁሉንም  የሚፈለጉትን መስክ መሞላቶን ያረጋግጡ!.
        /// </summary>
        public static string P_PH3 {
            get {
                return ResourceManager.GetString("P-PH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to መድረክ፣ የንግድ ዝርዝር እና አድራሻ.
        /// </summary>
        public static string P_PStep1 {
            get {
                return ResourceManager.GetString("P-PStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የተጠቃሚ መረጃ፣ የግል መረጃ፣ የሶስተኛ ወገኖች እና ኩኪዎች.
        /// </summary>
        public static string P_PStep2 {
            get {
                return ResourceManager.GetString("P-PStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ማስታወቂያ፣ ክትትል፣ ሃይፐርሊንኮች፣ ታዳሚዎች እና እውቂያ.
        /// </summary>
        public static string P_PStep3 {
            get {
                return ResourceManager.GetString("P-PStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ይክፈሉ.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ክፍያን ለማስኬድ.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ስልክ ቁጥር.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የክፍያ ሂደት እና መረጃ.
        /// </summary>
        public static string PPAndInfo {
            get {
                return ResourceManager.GetString("PPAndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የግላዊነት  መመሪያ ምንድን ነው እና ለምን ያስፈልገናል?.
        /// </summary>
        public static string PPH1 {
            get {
                return ResourceManager.GetString("PPH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የግላዊነት መመሪያ አንድ አካል የደንበኞችን ወይም የደንበኞችን መረጃ የሚሰበስብበትን፣ የሚጠቀምበትን፣ የሚገልጽበትን እና የሚያስተዳድርበትን አንዳንድ ወይም ሁሉንም መንገዶች የሚገልጽ መግለጫ ወይም ህጋዊ ሰነድ ነው። ለድረ-ገጻችን እና መተግበሪያ የግላዊነት መመሪያ ሊኖረን ይገባል ምክንያቱም የግለሰብ መረጃ መቼ ፣እንዴት እና ለምን ዓላማ በሌሎች እንደሚያዙ በራሳቸው የመወሰን ችሎታ ጋር ስለሚገናኝ። ግላዊነትን መጠበቅ የሰውን ክብር፣ ደህንነት እና ራስን መወሰን ለማረጋገጥ ቁልፍ ነው። ግለሰቦች በነፃነት የራሳቸውን ስብዕና እንዲያዳብሩ ያስችላቸዋል።.
        /// </summary>
        public static string PPH2 {
            get {
                return ResourceManager.GetString("PPH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ይህ የግላዊነት መመሪያ ለምን ነው ሚጠቀሙት?.
        /// </summary>
        public static string PPQ1 {
            get {
                return ResourceManager.GetString("PPQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ክ/ከተማ.
        /// </summary>
        public static string PPQ10 {
            get {
                return ResourceManager.GetString("PPQ10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ወረዳ.
        /// </summary>
        public static string PPQ11 {
            get {
                return ResourceManager.GetString("PPQ11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የቤት ቁጥር.
        /// </summary>
        public static string PPQ12 {
            get {
                return ResourceManager.GetString("PPQ12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ከተጠቃሚው የግል መረጃ ይሰበስባሉ?.
        /// </summary>
        public static string PPQ13 {
            get {
                return ResourceManager.GetString("PPQ13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ምን አይነት ውሂብ ነው የምትሰበስበው? አስፈላጊ ከሆነ ሁሉንም ይምረጡ.
        /// </summary>
        public static string PPQ14 {
            get {
                return ResourceManager.GetString("PPQ14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ለምን ዓላማ የግል መረጃን ይጠቀማሉ? .
        /// </summary>
        public static string PPQ15 {
            get {
                return ResourceManager.GetString("PPQ15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የእርስዎ ድህረገፅ የግል ውሂብን ለሶስተኛ ወገኖች ያጋራል? .
        /// </summary>
        public static string PPQ16 {
            get {
                return ResourceManager.GetString("PPQ16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የእርስዎ ድህረገፅ ኩኪዎችን ይጠቀማል? .
        /// </summary>
        public static string PPQ17 {
            get {
                return ResourceManager.GetString("PPQ17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የእርስዎ ድህረገፅ ለማስታወቂያ ዳግም ማሻሻጥ ይጠቀማል?.
        /// </summary>
        public static string PPQ18 {
            get {
                return ResourceManager.GetString("PPQ18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ለመከታተል ማንኛውንም ዲጂታል ሶፍትዌር ይጠቀማሉ?.
        /// </summary>
        public static string PPQ19 {
            get {
                return ResourceManager.GetString("PPQ19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድህረ ገጹ ወይም የመተግበሪያው ተቆጣታሪ ወይም አቀናባሪ?.
        /// </summary>
        public static string PPQ2 {
            get {
                return ResourceManager.GetString("PPQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የእርስዎ ድረ-ገጾች ሌሎች hyperlinks ይሰጣሉ?.
        /// </summary>
        public static string PPQ20 {
            get {
                return ResourceManager.GetString("PPQ20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድህረገፅ ተጠቃሚዎች ዕድሜ?.
        /// </summary>
        public static string PPQ21 {
            get {
                return ResourceManager.GetString("PPQ21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ተጠቃሚዎች እርስዎን እንዴት ማግኘት ይችላሉ?.
        /// </summary>
        public static string PPQ22 {
            get {
                return ResourceManager.GetString("PPQ22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የሚፀናበት ቀን.
        /// </summary>
        public static string PPQ23 {
            get {
                return ResourceManager.GetString("PPQ23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድህረ ገጹ ወይም የመተግበሪያ ስም.
        /// </summary>
        public static string PPQ3 {
            get {
                return ResourceManager.GetString("PPQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድህረ ገጹ  ወይም የመተግበሪያው ኦፕሬተር?.
        /// </summary>
        public static string PPQ4 {
            get {
                return ResourceManager.GetString("PPQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የኩባንያው ዓይነት.
        /// </summary>
        public static string PPQ5 {
            get {
                return ResourceManager.GetString("PPQ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የንግድ ስም.
        /// </summary>
        public static string PPQ6 {
            get {
                return ResourceManager.GetString("PPQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የንግዱ አድራሻ.
        /// </summary>
        public static string PPQ7 {
            get {
                return ResourceManager.GetString("PPQ7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ሀገር.
        /// </summary>
        public static string PPQ8 {
            get {
                return ResourceManager.GetString("PPQ8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ክልል.
        /// </summary>
        public static string PPQ9 {
            get {
                return ResourceManager.GetString("PPQ9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በዳሰሳ አሞሌው ላይ &quot;አመንጭ&quot; የሚለውን ይጫኑ.
        /// </summary>
        public static string PPStep1 {
            get {
                return ResourceManager.GetString("PPStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በሞሌው ውስጥ &quot;የግላዊነት መመሪያን ይምረጡ ወይም ከታች ያለዉን አዝራር ይጫኑ.
        /// </summary>
        public static string PPStep2 {
            get {
                return ResourceManager.GetString("PPStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ቅጾቹን በትክክል ይሙሉ እና ፣.
        /// </summary>
        public static string PPStep3 {
            get {
                return ResourceManager.GetString("PPStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በመጨረሻም አመንጭ የሚለውን ይጫኑ.
        /// </summary>
        public static string PPStep4 {
            get {
                return ResourceManager.GetString("PPStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የግላዊነት መመሪያ.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ምርቶችን እና አገልግሎቶችን ለማቅረብ.
        /// </summary>
        public static string Provide {
            get {
                return ResourceManager.GetString("Provide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የገበያ ጥናት ለማካሄድ.
        /// </summary>
        public static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to እንደገና ጀምር.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ቀጥል.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የቀድሞ መልሶችህን ከቆመበት መቀጠል ትፈልጋለህ?.
        /// </summary>
        public static string RP1 {
            get {
                return ResourceManager.GetString("RP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ስርዓትን ለማስኬድ እና ለማንቀሳቀስ.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ደህንነትን ለማረጋገጥ.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ይምረጡ.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ቋንቋ ይምረጡ.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ሶስተኛ ወገኖችን ይምረጡ.
        /// </summary>
        public static string SelectTP {
            get {
                return ResourceManager.GetString("SelectTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የመከታተያ ቴክኖሎጂ ዓይነቶችን ይምረጡ.
        /// </summary>
        public static string SelectTTT {
            get {
                return ResourceManager.GetString("SelectTTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አገልግሎቶች.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to እርምጃዎች.
        /// </summary>
        public static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ውሎች እና ሁኔታዎች በሁለት ቋንቋዎች (እንግሊዝኛ እና አማርኛ) መፍጠር ይችላሉ። ቅጹን ከመሙላትዎ በፊት የሚፈልጉትን ቋንቋ ይምረጡ። እንዲሁም እባክዎ መልሶችዎ በመረጡት ቋንቋ መሆናቸውን ያረጋግጡ። ተፈላጊ መስኮች..
        /// </summary>
        public static string T_CH1 {
            get {
                return ResourceManager.GetString("T-CH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የሚከተሉት ጥያቄዎች ትክክለኛ ውሎችን እና ሁኔታዎችን ለመፍጠር ይረዱናል። እባክዎን በጣም በጥንቃቄ ይመልሱዋቸው።.
        /// </summary>
        public static string T_CH2 {
            get {
                return ResourceManager.GetString("T-CH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to መድረክ፣ የንግድ ዝርዝር እና አድራሻ.
        /// </summary>
        public static string T_CStep1 {
            get {
                return ResourceManager.GetString("T-CStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አገልግሎቶች, መለያ እና ይዘቶች.
        /// </summary>
        public static string T_CStep2 {
            get {
                return ResourceManager.GetString("T-CStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የንግድ ምልክቶች፣ ማካካሻ እና እውቂያዎች.
        /// </summary>
        public static string T_CStep3 {
            get {
                return ResourceManager.GetString("T-CStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የመነጨ ሰነድ ለማውረድ ቴሌቢርን በመጠቀም 300ኢ..ቢ ይክፈሉ።.
        /// </summary>
        public static string TBP1 {
            get {
                return ResourceManager.GetString("TBP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የቴሌብር ክፍያ.
        /// </summary>
        public static string TBP2 {
            get {
                return ResourceManager.GetString("TBP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ደንብ እና ግዴታምንድን ነው እና ለምን ያስፈልገናል?.
        /// </summary>
        public static string TCH1 {
            get {
                return ResourceManager.GetString("TCH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ደንብ እና ግዴታ በእርስዎ እና በደንበኛዎ መካከል ለዕቃ ወይም ለአገልግሎት አቅርቦትዎ እና የንግድ ግንኙነቶን የሚቆጣጠረው የሕግ ውል ውሎች ናቸው። ከሌላ ሰው ጋር ንግድ ለመስራት የተስማሙበት ሁኔታ ናቸው።.
        /// </summary>
        public static string TCH2 {
            get {
                return ResourceManager.GetString("TCH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to እነዚህ ደንብ እና ግዴታዎች ለምን ጥቅም ላይ ይውላሉ?.
        /// </summary>
        public static string TCQ1 {
            get {
                return ResourceManager.GetString("TCQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የሚሰጡት አገልግሎት ምንድን ነው?.
        /// </summary>
        public static string TCQ10 {
            get {
                return ResourceManager.GetString("TCQ10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ተጠቃሚዎች መለያ መፍጠር ይችላሉ?.
        /// </summary>
        public static string TCQ11 {
            get {
                return ResourceManager.GetString("TCQ11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ተጠቃሚዎች መረጃ መለጠፍ ወይም ማጋራት ወይም ይዘት መስቀል ይችላሉ?.
        /// </summary>
        public static string TCQ12 {
            get {
                return ResourceManager.GetString("TCQ12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የተጠቃሚውን ይዘት ትጠቀማለህ?.
        /// </summary>
        public static string TCQ13 {
            get {
                return ResourceManager.GetString("TCQ13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የተጠቃሚዎችን የተለጠፈ ይዘት የመቀየር ወይም የመሰረዝ መብቱ የተጠበቀ ነው?.
        /// </summary>
        public static string TCQ14 {
            get {
                return ResourceManager.GetString("TCQ14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ለተጠቃሚዎች ጋዜጣዎችን ይልካሉ?.
        /// </summary>
        public static string TCQ15 {
            get {
                return ResourceManager.GetString("TCQ15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ጋዜጣዎችን እንዴት ይልካሉ?.
        /// </summary>
        public static string TCQ16 {
            get {
                return ResourceManager.GetString("TCQ16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የእርስዎ ድህረገፅ የሶስተኛ ወገን አገናኞችን ይሰጣሉ?.
        /// </summary>
        public static string TCQ17 {
            get {
                return ResourceManager.GetString("TCQ17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ለተጠቃሚዎችዎ የዕድሜ ገደብ አለዎት?.
        /// </summary>
        public static string TCQ18 {
            get {
                return ResourceManager.GetString("TCQ18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ድህረገጹ ታዳሚ ዕድሜ?.
        /// </summary>
        public static string TCQ19 {
            get {
                return ResourceManager.GetString("TCQ19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድህረ ገጹ ወይም የመተግበሪያው ተቆጣታሪ ወይም አቀናባሪ?.
        /// </summary>
        public static string TCQ2 {
            get {
                return ResourceManager.GetString("TCQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ተጠቃሚዎች የእርስዎን ድር ጣቢያ ለንግድ ዓላማ ይጠቀማሉ?.
        /// </summary>
        public static string TCQ20 {
            get {
                return ResourceManager.GetString("TCQ20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የእራስዎ ይዘት እና የንግድ ምልክቶች የእርስዎ ብቸኛ ንብረት መሆናቸውን ግልጽ ማድረግ ይፈልጋሉ?.
        /// </summary>
        public static string TCQ21 {
            get {
                return ResourceManager.GetString("TCQ21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በውሉ እና ሁኔታዎች ውስጥ የተጠያቂነት ገደብ እና የካሳ ክፍያን ማካተት ይፈልጋሉ?.
        /// </summary>
        public static string TCQ22 {
            get {
                return ResourceManager.GetString("TCQ22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የተጠቃሚ መለያዎችን የማቋረጥ መብት አሎት?.
        /// </summary>
        public static string TCQ23 {
            get {
                return ResourceManager.GetString("TCQ23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የተጠቃሚ መለያዎችን ከማቋረጡ በፊት ማስታወቂያ ይሰጣሉ?.
        /// </summary>
        public static string TCQ24 {
            get {
                return ResourceManager.GetString("TCQ24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ስለ ውሎችዎ እና ሁኔታዎችዎ ዝመናዎችን ለተጠቃሚዎችዎ ያሳውቃሉ?.
        /// </summary>
        public static string TCQ25 {
            get {
                return ResourceManager.GetString("TCQ25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ስለእነዚህ ውሎች እና ሁኔታዎች ማሻሻያ ለተጠቃሚዎችዎ እንዴት ያሳውቃሉ?.
        /// </summary>
        public static string TCQ26 {
            get {
                return ResourceManager.GetString("TCQ26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ተጠቃሚዎች እርስዎን እንዴት ማግኘት ይችላሉ?.
        /// </summary>
        public static string TCQ27 {
            get {
                return ResourceManager.GetString("TCQ27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የግፋ ማስታወቂያዎችን ለተጠቃሚዎች ይልካሉ?.
        /// </summary>
        public static string TCQ28 {
            get {
                return ResourceManager.GetString("TCQ28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድርጅቱ ዓይነት.
        /// </summary>
        public static string TCQ3 {
            get {
                return ResourceManager.GetString("TCQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የንግድ ስም.
        /// </summary>
        public static string TCQ4 {
            get {
                return ResourceManager.GetString("TCQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድህረገፅ URL ምንድን ነው?.
        /// </summary>
        public static string TCQ5 {
            get {
                return ResourceManager.GetString("TCQ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድህረጹ ወይም የመተግበሪያው ስም.
        /// </summary>
        public static string TCQ6 {
            get {
                return ResourceManager.GetString("TCQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የንግዱ አድራሻ.
        /// </summary>
        public static string TCQ7 {
            get {
                return ResourceManager.GetString("TCQ7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to የድህረገፅህ ላይ የግላዊነት ፖሊሲ አለህ?.
        /// </summary>
        public static string TCQ8 {
            get {
                return ResourceManager.GetString("TCQ8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አገናኙን(URL) ወደ የግላዊነት መመሪያዎ ያስቀምጡ.
        /// </summary>
        public static string TCQ9 {
            get {
                return ResourceManager.GetString("TCQ9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በዳሰሳ አሞሌው ላይ &quot;አመንጭ&quot; የሚለውን ይጫኑ.
        /// </summary>
        public static string TCStep1 {
            get {
                return ResourceManager.GetString("TCStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በሞሌው ውስጥ &quot; ደንብ እና ግዴታ’’ይምረጡ ወይም ከታች ያለውን አዝራር ይጫኑ.
        /// </summary>
        public static string TCStep2 {
            get {
                return ResourceManager.GetString("TCStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ቅጾቹን በትክክል ይሙሉ እና ፣.
        /// </summary>
        public static string TCStep3 {
            get {
                return ResourceManager.GetString("TCStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to በመጨረሻም አመንጭ የሚለውን ይጫኑ.
        /// </summary>
        public static string TCStep4 {
            get {
                return ResourceManager.GetString("TCStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ደንብ እና ግዴታ.
        /// </summary>
        public static string TermsAndCondition {
            get {
                return ResourceManager.GetString("TermsAndCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to አዎ.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
