//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivacyPolicyGeneratorFrontend.WebApp.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrivacyPolicyGeneratorFrontend.WebApp.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adey.
        /// </summary>
        public static string Adey {
            get {
                return ResourceManager.GetString("Adey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adey-Generator.
        /// </summary>
        public static string Adey_Generator {
            get {
                return ResourceManager.GetString("Adey-Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To show Ads.
        /// </summary>
        public static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back and change your answer.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To communicate with the user.
        /// </summary>
        public static string Communicate {
            get {
                return ResourceManager.GetString("Communicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Representer.
        /// </summary>
        public static string CompanyRepresenter {
            get {
                return ResourceManager.GetString("CompanyRepresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download PDF.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Imprint.
        /// </summary>
        public static string GenerateI {
            get {
                return ResourceManager.GetString("GenerateI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Privacy Policy.
        /// </summary>
        public static string GeneratePP {
            get {
                return ResourceManager.GetString("GeneratePP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Terms &amp; Condition.
        /// </summary>
        public static string GenerateTC {
            get {
                return ResourceManager.GetString("GenerateTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating....
        /// </summary>
        public static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        public static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Your Privacy Policy, Imprint, Terms &amp; Conditions.
        /// </summary>
        public static string Header1 {
            get {
                return ResourceManager.GetString("Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating your privacy policy, term and conditions,imprint for your website and applications could be stressful and time consuming. That is when we come in, we have provided you with a platform where with just answering a few questions all is done. Compliant with Ethiopian data..
        /// </summary>
        public static string Header2 {
            get {
                return ResourceManager.GetString("Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy and fast payment with Telebirr.
        /// </summary>
        public static string HPTB1 {
            get {
                return ResourceManager.GetString("HPTB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online payment has been integrated with Telebirr. After you finish answering questions you&apos;ll be prompted to pay online using Telebirr. you can&apos;t download or copy and paste generated documents without payment confirmation..
        /// </summary>
        public static string HPTB2 {
            get {
                return ResourceManager.GetString("HPTB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300 ETB / Document.
        /// </summary>
        public static string HPTB3 {
            get {
                return ResourceManager.GetString("HPTB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can generate Imprint in two languages (English and Amharic). choose your preferred language before filling out the form. also please make sure that your answers are in your preferred language. required fields..
        /// </summary>
        public static string I_H1 {
            get {
                return ResourceManager.GetString("I-H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following questions help us generate an accurate Imprint. please answer them very carefully..
        /// </summary>
        public static string I_H2 {
            get {
                return ResourceManager.GetString("I-H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is an Imprint and why do we need it?.
        /// </summary>
        public static string IH1 {
            get {
                return ResourceManager.GetString("IH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Imprint is essentially a statement of ownership and authorship. It was put into place in an effort to protect user data, combat illegal content and spam by making website owners identify themselves, and as a result assume responsibility for the content on their platform..
        /// </summary>
        public static string IH2 {
            get {
                return ResourceManager.GetString("IH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint.
        /// </summary>
        public static string Imprint {
            get {
                return ResourceManager.GetString("Imprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Improve &amp; develop the service.
        /// </summary>
        public static string Improve {
            get {
                return ResourceManager.GetString("Improve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string IQ1 {
            get {
                return ResourceManager.GetString("IQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Company .
        /// </summary>
        public static string IQ2 {
            get {
                return ResourceManager.GetString("IQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string IQ3 {
            get {
                return ResourceManager.GetString("IQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Address.
        /// </summary>
        public static string IQ4 {
            get {
                return ResourceManager.GetString("IQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Register Number .
        /// </summary>
        public static string IQ5 {
            get {
                return ResourceManager.GetString("IQ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat ID.
        /// </summary>
        public static string IQ6 {
            get {
                return ResourceManager.GetString("IQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number.
        /// </summary>
        public static string IQ7 {
            get {
                return ResourceManager.GetString("IQ7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who Represents The Company.
        /// </summary>
        public static string IQ8 {
            get {
                return ResourceManager.GetString("IQ8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your website provide other website links?.
        /// </summary>
        public static string IQ9 {
            get {
                return ResourceManager.GetString("IQ9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &quot;Generate&quot; on navigation bar.
        /// </summary>
        public static string IStep1 {
            get {
                return ResourceManager.GetString("IStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &quot;Imprint&quot; in the menu or click a button bellow.
        /// </summary>
        public static string IStep2 {
            get {
                return ResourceManager.GetString("IStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the forms accordingly and,.
        /// </summary>
        public static string Istep3 {
            get {
                return ResourceManager.GetString("Istep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally click Generate.
        /// </summary>
        public static string Istep4 {
            get {
                return ResourceManager.GetString("Istep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bole Subcity Woreda 12.
        /// </summary>
        public static string Office1 {
            get {
                return ResourceManager.GetString("Office1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House number: New.
        /// </summary>
        public static string Office2 {
            get {
                return ResourceManager.GetString("Office2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addis Ababa, Ethiopia.
        /// </summary>
        public static string Office3 {
            get {
                return ResourceManager.GetString("Office3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List other Data you collect separated by comma(,).
        /// </summary>
        public static string OtherDatas {
            get {
                return ResourceManager.GetString("OtherDatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List other purposes separated by comma(,).
        /// </summary>
        public static string OtherPusposes {
            get {
                return ResourceManager.GetString("OtherPusposes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a privacy policy in two languages ​​(English and Amharic). Please select your preferred language before filling out the form. Also, please ensure that your answers are in the language of your choice. Required fields..
        /// </summary>
        public static string P_PH1 {
            get {
                return ResourceManager.GetString("P-PH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following questions help us generate an accurate privacy policy. please answer them very carefully..
        /// </summary>
        public static string P_PH2 {
            get {
                return ResourceManager.GetString("P-PH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button will be active when you finish filling the forms. make sure you selected language and every required field is filled!.
        /// </summary>
        public static string P_PH3 {
            get {
                return ResourceManager.GetString("P-PH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform, Business Detail &amp; Address.
        /// </summary>
        public static string P_PStep1 {
            get {
                return ResourceManager.GetString("P-PStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Info, Personal Data, Third parties &amp; Cookies.
        /// </summary>
        public static string P_PStep2 {
            get {
                return ResourceManager.GetString("P-PStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising, Tracking, Hyperlinks, Audience &amp; Contact.
        /// </summary>
        public static string P_PStep3 {
            get {
                return ResourceManager.GetString("P-PStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Now.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To process payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Processing and Info.
        /// </summary>
        public static string PPAndInfo {
            get {
                return ResourceManager.GetString("PPAndInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a Privacy Policy and why do we need it?.
        /// </summary>
        public static string PPH1 {
            get {
                return ResourceManager.GetString("PPH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Privacy Policy is a statement or legal document that discloses some or all of the ways a party gathers, uses, discloses and manages a customers or clients data. We need to have a privacy policy for our website and application because it relates to an individual’s ability to determine for themselves when, how and for what purpose their personal information is handled by others. Protecting privacy is key to ensuring human dignity, safety and self-determination. It allows individuals freely develop their own [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PPH2 {
            get {
                return ResourceManager.GetString("PPH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Privacy Policy will be used for?.
        /// </summary>
        public static string PPQ1 {
            get {
                return ResourceManager.GetString("PPQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-City.
        /// </summary>
        public static string PPQ10 {
            get {
                return ResourceManager.GetString("PPQ10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woreda.
        /// </summary>
        public static string PPQ11 {
            get {
                return ResourceManager.GetString("PPQ11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Number.
        /// </summary>
        public static string PPQ12 {
            get {
                return ResourceManager.GetString("PPQ12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you collect personal information from the user?.
        /// </summary>
        public static string PPQ13 {
            get {
                return ResourceManager.GetString("PPQ13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of data do you collect? check all if applicable.
        /// </summary>
        public static string PPQ14 {
            get {
                return ResourceManager.GetString("PPQ14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For what purpose do you use personal Data? .
        /// </summary>
        public static string PPQ15 {
            get {
                return ResourceManager.GetString("PPQ15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your website share personal data with third parties? .
        /// </summary>
        public static string PPQ16 {
            get {
                return ResourceManager.GetString("PPQ16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do your website use cookies?.
        /// </summary>
        public static string PPQ17 {
            get {
                return ResourceManager.GetString("PPQ17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your website use remarketing for Advertising? .
        /// </summary>
        public static string PPQ18 {
            get {
                return ResourceManager.GetString("PPQ18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you use any digital software for tracking? .
        /// </summary>
        public static string PPQ19 {
            get {
                return ResourceManager.GetString("PPQ19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website URL.
        /// </summary>
        public static string PPQ2 {
            get {
                return ResourceManager.GetString("PPQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do your website provide other hyperlinks? .
        /// </summary>
        public static string PPQ20 {
            get {
                return ResourceManager.GetString("PPQ20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Website Audience age? .
        /// </summary>
        public static string PPQ21 {
            get {
                return ResourceManager.GetString("PPQ21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can users contact you?.
        /// </summary>
        public static string PPQ22 {
            get {
                return ResourceManager.GetString("PPQ22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose effective date. .
        /// </summary>
        public static string PPQ23 {
            get {
                return ResourceManager.GetString("PPQ23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website or App Name .
        /// </summary>
        public static string PPQ3 {
            get {
                return ResourceManager.GetString("PPQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator of the website or app? .
        /// </summary>
        public static string PPQ4 {
            get {
                return ResourceManager.GetString("PPQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Company.
        /// </summary>
        public static string PPQ5 {
            get {
                return ResourceManager.GetString("PPQ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Business .
        /// </summary>
        public static string PPQ6 {
            get {
                return ResourceManager.GetString("PPQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of the Business .
        /// </summary>
        public static string PPQ7 {
            get {
                return ResourceManager.GetString("PPQ7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string PPQ8 {
            get {
                return ResourceManager.GetString("PPQ8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string PPQ9 {
            get {
                return ResourceManager.GetString("PPQ9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Generate&quot; on navigation bar.
        /// </summary>
        public static string PPStep1 {
            get {
                return ResourceManager.GetString("PPStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &quot;Privacy Policy&quot; in the menu or click a button bellow.
        /// </summary>
        public static string PPStep2 {
            get {
                return ResourceManager.GetString("PPStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the forms accordingly and,.
        /// </summary>
        public static string PPStep3 {
            get {
                return ResourceManager.GetString("PPStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally click Generate.
        /// </summary>
        public static string PPStep4 {
            get {
                return ResourceManager.GetString("PPStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To provide products &amp; services.
        /// </summary>
        public static string Provide {
            get {
                return ResourceManager.GetString("Provide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To perform market research.
        /// </summary>
        public static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to resume your previous answers?.
        /// </summary>
        public static string RP1 {
            get {
                return ResourceManager.GetString("RP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To run &amp; operate the site.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ensure security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Third Parties.
        /// </summary>
        public static string SelectTP {
            get {
                return ResourceManager.GetString("SelectTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tracking Tech Types.
        /// </summary>
        public static string SelectTTT {
            get {
                return ResourceManager.GetString("SelectTTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can generate Terms and Conditions in two languages (English and Amharic). choose your prefered language before filling out the form. also please make sure that your answers are in your prefered language. required fields..
        /// </summary>
        public static string T_CH1 {
            get {
                return ResourceManager.GetString("T-CH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following questions help us generate accurate terms and conditions. please answer them very carefully..
        /// </summary>
        public static string T_CH2 {
            get {
                return ResourceManager.GetString("T-CH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform, Business Detail and Address.
        /// </summary>
        public static string T_CStep1 {
            get {
                return ResourceManager.GetString("T-CStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services, Account and Contents.
        /// </summary>
        public static string T_CStep2 {
            get {
                return ResourceManager.GetString("T-CStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trademarks, Indemnification and Contacts.
        /// </summary>
        public static string T_CStep3 {
            get {
                return ResourceManager.GetString("T-CStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To download generated document please pay 300ETB using telebirr!.
        /// </summary>
        public static string TBP1 {
            get {
                return ResourceManager.GetString("TBP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telebirr Payment.
        /// </summary>
        public static string TBP2 {
            get {
                return ResourceManager.GetString("TBP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are Terms and Conditions and their use?.
        /// </summary>
        public static string TCH1 {
            get {
                return ResourceManager.GetString("TCH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions are the terms of the legal contract between you and your customer for your supply of goods or service, and which regulates your business relationship. They are the condition on which you agree to do business with someone else..
        /// </summary>
        public static string TCH2 {
            get {
                return ResourceManager.GetString("TCH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These terms and conditions will be used for? .
        /// </summary>
        public static string TCQ1 {
            get {
                return ResourceManager.GetString("TCQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the service you provide?.
        /// </summary>
        public static string TCQ10 {
            get {
                return ResourceManager.GetString("TCQ10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can users create accounts?.
        /// </summary>
        public static string TCQ11 {
            get {
                return ResourceManager.GetString("TCQ11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can users post or share information or upload content?.
        /// </summary>
        public static string TCQ12 {
            get {
                return ResourceManager.GetString("TCQ12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you use user’s content?.
        /// </summary>
        public static string TCQ13 {
            get {
                return ResourceManager.GetString("TCQ13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you reserve the right to modify or delete users posted content?.
        /// </summary>
        public static string TCQ14 {
            get {
                return ResourceManager.GetString("TCQ14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you send newsletters to users?.
        /// </summary>
        public static string TCQ15 {
            get {
                return ResourceManager.GetString("TCQ15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you send newsletters? .
        /// </summary>
        public static string TCQ16 {
            get {
                return ResourceManager.GetString("TCQ16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do your websites provide third-party links?.
        /// </summary>
        public static string TCQ17 {
            get {
                return ResourceManager.GetString("TCQ17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have an age limitation for your users?.
        /// </summary>
        public static string TCQ18 {
            get {
                return ResourceManager.GetString("TCQ18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Website Audience age? .
        /// </summary>
        public static string TCQ19 {
            get {
                return ResourceManager.GetString("TCQ19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator of the website or app? .
        /// </summary>
        public static string TCQ2 {
            get {
                return ResourceManager.GetString("TCQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do users use your website for commercial purposes?.
        /// </summary>
        public static string TCQ20 {
            get {
                return ResourceManager.GetString("TCQ20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to make it clear that your own content and trademarks are your exclusive property?.
        /// </summary>
        public static string TCQ21 {
            get {
                return ResourceManager.GetString("TCQ21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to include limitation of liability and indemnification in the terms and conditions?.
        /// </summary>
        public static string TCQ22 {
            get {
                return ResourceManager.GetString("TCQ22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have the right to terminate user accounts?.
        /// </summary>
        public static string TCQ23 {
            get {
                return ResourceManager.GetString("TCQ23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you give notice before terminating user accounts??.
        /// </summary>
        public static string TCQ24 {
            get {
                return ResourceManager.GetString("TCQ24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you notify your users of the updates to your terms and conditions?.
        /// </summary>
        public static string TCQ25 {
            get {
                return ResourceManager.GetString("TCQ25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you notify your users about the updates to these terms and conditions?.
        /// </summary>
        public static string TCQ26 {
            get {
                return ResourceManager.GetString("TCQ26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can users contact you?.
        /// </summary>
        public static string TCQ27 {
            get {
                return ResourceManager.GetString("TCQ27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you send push notifications to users?.
        /// </summary>
        public static string TCQ28 {
            get {
                return ResourceManager.GetString("TCQ28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Company .
        /// </summary>
        public static string TCQ3 {
            get {
                return ResourceManager.GetString("TCQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name .
        /// </summary>
        public static string TCQ4 {
            get {
                return ResourceManager.GetString("TCQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what is the URL of your website? .
        /// </summary>
        public static string TCQ5 {
            get {
                return ResourceManager.GetString("TCQ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the website or app .
        /// </summary>
        public static string TCQ6 {
            get {
                return ResourceManager.GetString("TCQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of the Business.
        /// </summary>
        public static string TCQ7 {
            get {
                return ResourceManager.GetString("TCQ7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a privacy policy on your website?.
        /// </summary>
        public static string TCQ8 {
            get {
                return ResourceManager.GetString("TCQ8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put the link to your privacy policy.
        /// </summary>
        public static string TCQ9 {
            get {
                return ResourceManager.GetString("TCQ9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &quot;Generate&quot; on navigation bar.
        /// </summary>
        public static string TCStep1 {
            get {
                return ResourceManager.GetString("TCStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &quot;Terms &amp; Conditions&quot; in the menu or click a button bellow.
        /// </summary>
        public static string TCStep2 {
            get {
                return ResourceManager.GetString("TCStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the forms accordingly and,.
        /// </summary>
        public static string TCStep3 {
            get {
                return ResourceManager.GetString("TCStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally click Generate.
        /// </summary>
        public static string TCStep4 {
            get {
                return ResourceManager.GetString("TCStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string TermsAndCondition {
            get {
                return ResourceManager.GetString("TermsAndCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
